"""empty message

Revision ID: 10671722f1a0
Revises: 29b052ee87b4
Create Date: 2015-01-28 11:56:28.215945

"""

# revision identifiers, used by Alembic.
revision = '10671722f1a0'
down_revision = '29b052ee87b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karty',
    sa.Column('id_zaznamu', sa.Integer(), nullable=False),
    sa.Column('cislo_karty', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('datum_pridani_zaznamu', sa.DateTime(), nullable=False)

    )
    op.create_index('cislo_karty', unique=False)


    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_prijmeni', 'loguser', ['prijmeni'], unique=False)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cislo_karty', table_name='karty')
    op.drop_table('karty')

    op.drop_index('ix_loguser_prijmeni', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
